#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ChildMath.Resource", IsApplication=true)]

namespace ChildMath
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050001
			public const int floor_count = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int question_count = 2131034112;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int bck = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int button_answer = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int question = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int question_count = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int start_button = 2130837509;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f07000e
			public const int btnAnswer = 2131165198;
			
			// aapt resource value: 0x7f070007
			public const int btnStart = 2131165191;
			
			// aapt resource value: 0x7f070008
			public const int gridview = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int gridviewNumbers = 2131165193;
			
			// aapt resource value: 0x7f07000d
			public const int lblAnswer = 2131165197;
			
			// aapt resource value: 0x7f07000a
			public const int lblNumber1 = 2131165194;
			
			// aapt resource value: 0x7f07000c
			public const int lblNumber2 = 2131165196;
			
			// aapt resource value: 0x7f07000f
			public const int lblQuestionCount = 2131165199;
			
			// aapt resource value: 0x7f07000b
			public const int lblSymbols = 2131165195;
			
			// aapt resource value: 0x7f070006
			public const int pcFloor = 2131165190;
			
			// aapt resource value: 0x7f070005
			public const int pcQuestionCount = 2131165189;
			
			// aapt resource value: 0x7f070004
			public const int swDivision = 2131165188;
			
			// aapt resource value: 0x7f070003
			public const int swMultiplication = 2131165187;
			
			// aapt resource value: 0x7f070002
			public const int swSubtraction = 2131165186;
			
			// aapt resource value: 0x7f070001
			public const int swaddition = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int textView2 = 2131165184;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int QuestionViewLayout = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int CustomTheme = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
